name: Y2021

on:
  push:
    paths:
      - '2021/Y2021/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./2021/Y2021/Y2021.csproj
    - name: Build
      run: dotnet build ./2021/Y2021/Y2021.csproj --no-restore
    - name: Test
      run: dotnet test ./2021/Y2021/Y2021.csproj --no-build --verbosity normal
      
  benchmarks:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./2021/Benchmarks/Benchmarks.csproj
    - name: Build
      run: dotnet build ./2021/Benchmarks/Benchmarks.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet run --project ./2021/Benchmarks/Benchmarks.csproj --configuration Release --no-build
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: | 
           Rename-Item -Path "BenchmarkDotNet.Artifacts/results/Benchmarks.BenchmarksRunner-report-github.md" -NewName "README.md"
           Copy-Item "BenchmarkDotNet.Artifacts/results/README.md" -Destination "."
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        add: README.md
        author_name: "Automation"
        message: "Update Benchamrks"

